# Edge ConfigMap 
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-edge-runtime
  namespace: edge-deployment
data:
  SAG_IS_CLOUD_REGISTER_TOKEN: d97210488b5c49da8dc
  SAG_IS_CLOUD_REGISTER_URL: https://wmintanywhere.int-aw-au.webmethods.io
  SAG_IS_EDGE_CLOUD_ALIAS: EdgeRuntime_NL_MIHE_K8S
  SAG_IS_HEALTH_ENDPOINT_ACL: Anonymous
  SAG_IS_CLOUD_ALLOWSYNC: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-properties-is
  namespace: "edge-deployment"
data:
  application.properties: |
    healthindicators.Adapters.enabled=true
    healthindicators.Cluster.enabled=true
    healthindicators.Cluster.properties.threshold.value=2
    healthindicators.Diskspace.enabled=true
    healthindicators.Diskspace.properties.threshold.value=10
    healthindicators.JDBC.enabled=true
    healthindicators.JMS.enabled=true
    healthindicators.JNDIAliases.enabled=false
    healthindicators.Memory.enabled=true
    healthindicators.Memory.properties.threshold.value=10
    healthindicators.RemoteServers.enabled=true
    healthindicators.SFTPServers.enabled=true
    healthindicators.ServiceThread.enabled=true
    healthindicators.ServiceThread.properties.threshold.value=10
    healthindicators.Sessions.enabled=true
    healthindicators.Sessions.properties.threshold.value=85
    healthindicators.UMAliases.enabled=true
    jms.DEFAULT_IS_JMS_CONNECTION.clientID=DEFAULT_IS_JMS_CLIENT
    jndi.DEFAULT_IS_JNDI_PROVIDER.providerURL=nsp\://universalmessaging.swag-infra\:9000