apiVersion: v1
kind: Service
metadata:
  labels:
    app: wm-edge-runtime
  name: wm-edge-runtime-service
  namespace: swag-infra
spec: 
  ports:
    - name: api-container-tcp
      port: 5555
      protocol: TCP
      targetPort: 5555
  selector:
    app: wm-edge-runtime
  type: LoadBalancer