apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${CONTAINER}
  name: ${CONTAINER}-service
  namespace: ${NAMESPACE}
spec: 
  ports:
    - name: api-container-tcp
      port: 5555
      protocol: TCP
      targetPort: 5555
  selector:
    app: ${CONTAINER}
  type: LoadBalancer